name = "Ariadne"
uuid = "0be81120-40bf-4f8b-adf0-26103efb66f1"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DifferentiationInterface = "0.7.14"
Enzyme = "0.13.50"
Krylov = "0.10.1"
LinearAlgebra = "1.10"
julia = "1.10"
